[theme]
base="light"
primaryColor="#0d6efd"
backgroundColor="#ffffffff"
secondaryBackgroundColor="#ffffffff"
textColor="#000000ff"
font="sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
